# .github/workflows/ci.yml
name: ci
on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [apps/mercury-js, apps/mercury-ts]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ matrix.app }}/package-lock.json
      - name: Install deps
        working-directory: ${{ matrix.app }}
        run: npm ci --no-audit --no-fund
      - run: npm run lint
        working-directory: ${{ matrix.app }}
      - run: npm run typecheck || true
        working-directory: ${{ matrix.app }}
      - run: npm run test
        working-directory: ${{ matrix.app }}
